sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kalpu001/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kalpu001/docker-react npm run test
